//---TownNeighborsSystem

switch (toLower(worldName)) do {
	case "altis": {
		Selakano setVariable ["cti_town_neighbors",[Feres,ComPlatform]];
		Pyrgos setVariable ["cti_town_neighbors",[SubPen,Faronaki,Ekali,Dorida]];
		Dorida setVariable ["cti_town_neighbors",[Chalkeia,Pyrgos,Charkia]];
		Charkia setVariable ["cti_town_neighbors",[Rodopoli,Dorida,Anthrakia]];
		Kalochori setVariable ["cti_town_neighbors",[Paros,Limni]];
		Rodopoli setVariable ["cti_town_neighbors",[Kalithea,Paros,Charkia]];
		Paros setVariable ["cti_town_neighbors",[Rodopoli,Loannina,MilitaryOutpost,Limni,Kalochori]];
		Molos setVariable ["cti_town_neighbors",[Sofia,ResearchPlatform,MolosAirfield]];
		Anthrakia setVariable ["cti_town_neighbors",[Telos,Charkia,SubPen]];
		Telos setVariable ["cti_town_neighbors",[Military,Kalithea,Anthrakia]];
		Athira setVariable ["cti_town_neighbors",[Military,Ifestiona,Frini]];
		Koroni setVariable ["cti_town_neighbors",[Galati,Ifestiona,Lakka]];
		Galati setVariable ["cti_town_neighbors",[Koroni,Syrta,NorthAirfield]];
		Oreokastro setVariable ["cti_town_neighbors",[NorthAirfield,AgiosKonstantinos,TheDump]];
		Syrta setVariable ["cti_town_neighbors",[Kore,AgiosDionysios,Galati,TheDump]];
		AgiosDionysios setVariable ["cti_town_neighbors",[Lakka,Zaros,Kore,Syrta]];
		Lakka setVariable ["cti_town_neighbors",[Neochori,AirBase,Koroni,AgiosDionysios]];
		Neochori setVariable ["cti_town_neighbors",[AirBase,Lakka,Military,SubPen,AACAirfield]];
		Zaros setVariable ["cti_town_neighbors",[AgiosDionysios,AACAirfield,Vikos,Panochori]];
		Kavala setVariable ["cti_town_neighbors",[Panochori,WindFarm,Stadium]];
		Airbase setVariable ["cti_town_neighbors",[Neochori,Lakka,Military,SubPen]];
		Military setVariable ["cti_town_neighbors",[Athira,Telos,Airbase]];
		Chalkeia setVariable ["cti_town_neighbors",[Dorida,Panagia,Limni]];
		Ifestiona setVariable ["cti_town_neighbors",[Koroni,Athira,Frini]];
		Negades setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kore,Stadium]];
		Sofia setVariable ["cti_town_neighbors",[Molos,Nidasos,Loannina]];
		Panagia setVariable ["cti_town_neighbors",[Chalkeia,Feres,Ekali]];
		Kore setVariable ["cti_town_neighbors",[Syrta,AgiosDionysios,Negades]];
		SandAirfield setVariable ["cti_town_neighbors",[Loannina]];
		Makrynisi setVariable ["cti_town_neighbors",[Faronaki,Neochori,AACAirfield]];
		Faronaki setVariable ["cti_town_neighbors",[Ekali,Vikos,Makrynisi,Pyrgos]];
		Kalithea setVariable ["cti_town_neighbors",[Rodopoli,Telos]];
		Vikos setVariable ["cti_town_neighbors",[Zaros,Faronaki,ComPlatform,OilRig]];
		Ekali setVariable ["cti_town_neighbors",[Panagia,Faronaki,ComPlatform,Pyrgos]];
		Frini setVariable ["cti_town_neighbors",[Ifestiona,Nychi,Athira,RadarPlatform]];
		Nychi setVariable ["cti_town_neighbors",[TheaterRuins,FuelDepot,Frini]];
		TheaterRuins setVariable ["cti_town_neighbors",[FuelDepot,MilitaryOutpost,Nychi]];
		MilitaryOutpost setVariable ["cti_town_neighbors",[TheaterRuins,Paros,HotelComplex]];
		NorthAirfield setVariable ["cti_town_neighbors",[Galati,Oreokastro,RadarPlatform]];
		Loannina setVariable ["cti_town_neighbors",[SandAirfield,Sofia,HotelComplex,Paros]];
		AACAirfield setVariable ["cti_town_neighbors",[Zaros,Neochori,Makrynisi]];
		MolosAirfield setVariable ["cti_town_neighbors",[FuelDepot,Molos]];
		Panochori setVariable ["cti_town_neighbors",[Kavala,Stadium,Zaros,OilRig]];
		HotelComplex setVariable ["cti_town_neighbors",[MilitaryOutpost,Loannina,Nidasos]];
		Stadium setVariable ["cti_town_neighbors",[Negades,Kavala,Panochori]];
		Limni setVariable ["cti_town_neighbors",[Paros,Chalkeia,ResearchPlatform]];
		AgiosKonstantinos setVariable ["cti_town_neighbors",[TheDump,Negades,Oreokastro,WindFarm]];
		Feres setVariable ["cti_town_neighbors",[Panagia,Selakano,ResearchPlatform]];
		Thedump setVariable ["cti_town_neighbors",[Oreokastro,Syrta,AgiosKonstantinos]];
		Nidasos setVariable ["cti_town_neighbors",[HotelComplex,Sofia]];
		SubPen setVariable ["cti_town_neighbors",[Neochori,Airbase,Anthrakia,Pyrgos]];
		ComPlatform setVariable ["cti_town_neighbors",[Ekali,Vikos,Selakano]];
		ResearchPlatform setVariable ["cti_town_neighbors",[Feres,Limni,Molos]];
		FuelDepot setVariable ["cti_town_neighbors",[RadarPlatform,Nychi,TheaterRuins,NorthAirfield]];
		OilRig setVariable ["cti_town_neighbors",[Vikos,Panochori]];
		RadarPlatform setVariable ["cti_town_neighbors",[NorthAirfield,Frini,FuelDepot]];
		WindFarm setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kavala]];
	};
};

switch (toLower(worldName)) do {
	case "stratis": {
		BayOutpost setVariable ["cti_town_neighbors",[AgiaMarina,ComPlatform,KillFarm]];
		KillFarm setVariable ["cti_town_neighbors",[Junction,BayOutpost]];
		Junction setVariable ["cti_town_neighbors",[CampRogain,KillFarm,AgiaMarina,MilitaryRange]];
		AgiaMarina setVariable ["cti_town_neighbors",[Junction,BayOutpost,MilitaryRange,AirbaseOutpost]];
		AirbaseOutpost setVariable ["cti_town_neighbors",[AgiaMarina,MilitaryRange,TransmissionTowerBrit,AirBase,OysterBay]];
		AirBase setVariable ["cti_town_neighbors",[ComPlatform,AirField,AirbaseOutpost]];
		AirField setVariable ["cti_town_neighbors",[AirBase,FuelDepot,OysterBay]];
		MilitaryRange setVariable ["cti_town_neighbors",[AgiaMarina,AirbaseOutpost,StorageDump,Junction]];
		StorageDump setVariable ["cti_town_neighbors",[MilitaryRange,CampRogain,TransmissionTowerBrit,CheckpointBravo]];
		CampRogain setVariable ["cti_town_neighbors",[RadioControl,KaminoVillage,Junction,StorageDump]];
		RadioControl setVariable ["cti_town_neighbors",[CheckpointCharlie,OldRuins,CampRogain]];
		KaminoVillage setVariable ["cti_town_neighbors",[KaminoFiringRange,CampRogain]];
		KaminoFiringRange setVariable ["cti_town_neighbors",[OldRuins,SubPen,KaminoVillage]];
		OldRuins setVariable ["cti_town_neighbors",[RadioControl,KaminoFiringRange]];
		LimeriBay setVariable ["cti_town_neighbors",[CheckpointCharlie,SubPen]];
		TransmissionTowerBrit setVariable ["cti_town_neighbors",[CheckpointBravo,AirbaseOutpost,StorageDump,OysterBay]];
		CheckpointBravo setVariable ["cti_town_neighbors",[OldOutpost,TransmissionTowerBrit,StorageDump]];
		CheckpointCharlie setVariable ["cti_town_neighbors",[OldOutpost,LimeriBay,RadioControl]];
		CheckpointMike setVariable ["cti_town_neighbors",[CampMaxwell,Tsoukalia,AirStationMike]];
		OldOutpost setVariable ["cti_town_neighbors",[AirStationMike,CheckpointBravo,CheckpointCharlie]];
		CampTempest setVariable ["cti_town_neighbors",[FuelDepot,TempestOutpost]];
		TempestOutpost setVariable ["cti_town_neighbors",[CampTempest,NisiBay,AirStationMike]];
		NisiBay setVariable ["cti_town_neighbors",[TempestOutpost,OysterBay]];
		AirStationMike setVariable ["cti_town_neighbors",[CheckpointMike,TempestOutpost,OldOutpost]];
		OysterBay setVariable ["cti_town_neighbors",[NisiBay,AirField,TransmissionTowerBrit,AirbaseOutpost]];
		Tsoukalia setVariable ["cti_town_neighbors",[CheckpointMike,SubPen]];
		CampMaxwell setVariable ["cti_town_neighbors",[LZConnor,CheckpointMike,Girna]];
		Girna setVariable ["cti_town_neighbors",[CampMaxwell,StrogosBay,FuelDepot]];
		LZConnor setVariable ["cti_town_neighbors",[JayCove,StrogosBay,CampMaxwell,SubPen]];
		StrogosBay setVariable ["cti_town_neighbors",[LZConnor,FuelDepot,Girna,JayCove]];
		JayCove setVariable ["cti_town_neighbors",[LZConnor,StrogosBay]];
		SubPen setVariable ["cti_town_neighbors",[LZConnor,Tsoukalia,LimeriBay,KaminoFiringRange]];
		ComPlatform setVariable ["cti_town_neighbors",[BayOutpost,AirBase]];
		FuelDepot setVariable ["cti_town_neighbors",[StrogosBay,AirField,CampTempest,Girna]];
	};
};

switch (toLower(worldName)) do {
	case "tanoa": {
		Tuvanaka setVariable ["cti_town_neighbors", [TuvanakaAirbase,Belfort]];
		TuvanakaAirbase setVariable ["cti_town_neighbors", [Tuvanaka,CampRemnants]];
		Nani setVariable ["cti_town_neighbors", [Belfort,WindFarm,Sosovu]];
		Belfort setVariable ["cti_town_neighbors", [Tuvanaka,HarborRemnants,Nani]];
		HarborRemnants setVariable ["cti_town_neighbors", [Belfort,CampRemnants,OuaQueLumberyard]];
		CampRemnants setVariable ["cti_town_neighbors", [TuvanakaAirbase,HarborRemnants,lleSainteMarie]];
		WindFarm setVariable ["cti_town_neighbors", [Nani,Muaceba]];
		Sosovu setVariable ["cti_town_neighbors", [Muaceba,Regina]];
		Muaceba setVariable ["cti_town_neighbors", [WindFarm,Sosovu,Tavu,Balavu]];
		Tavu setVariable ["cti_town_neighbors", [Muaceba,Balavu,Laikoro]];
		Balavu setVariable ["cti_town_neighbors", [Muaceba,Tavu,Laikoro,Rautake]];
		Laikoro setVariable ["cti_town_neighbors", [Tavu,Balavu,Namuvaka]];
		Namuvaka setVariable ["cti_town_neighbors", [Laikoro,Rautake,Cerebu]];
		Rautake setVariable ["cti_town_neighbors", [Balavu,Namuvaka,Ferry]];
		Cerebu setVariable ["cti_town_neighbors", [Namuvaka,Yanukka]];
		Koumac setVariable ["cti_town_neighbors", [Lailai,Yanukka]];
		Yanukka setVariable ["cti_town_neighbors", [Lailai,Cerebu,Koumac]];
		Lailai setVariable ["cti_town_neighbors", [Katkoula,Yanukka,Koumac]];
		Ferry setVariable ["cti_town_neighbors", [Rautake,Katkoula]];
		Katkoula setVariable ["cti_town_neighbors", [Ferry,Savaka,Lailai]];
		Savaka setVariable ["cti_town_neighbors", [Katkoula,OilRig,Moddergat]];
		OilRig setVariable ["cti_town_neighbors", [Savaka,Moddergat,TuaduaIsland]];
		TuaduaIsland setVariable ["cti_town_neighbors", [OilRig,Blerick]];
		Moddergat setVariable ["cti_town_neighbors", [Savaka,OilRig,Losi,Blerick]];
		Losi setVariable ["cti_town_neighbors", [Moddergat,Harcourt]];
		Harcourt setVariable ["cti_town_neighbors", [Doodstil,Losi,Kotomo]];
		Doodstil setVariable ["cti_town_neighbors", [PortBoise,Harcourt,FuelDepot]];
		PortBoise setVariable ["cti_town_neighbors", [Lijnhaven,Rereki,Doodstil]];
		Lijnhaven setVariable ["cti_town_neighbors", [Blerick,PortBoise,Rereki]];
		Rereki setVariable ["cti_town_neighbors", [Lijnhaven,PortBoise]];
		Blerick setVariable ["cti_town_neighbors", [TuaduaIsland,Moddergat,Lijnhaven]];
		FuelDepot setVariable ["cti_town_neighbors", [Doodstil,Oumere]];
		lleSainteMarie setVariable ["cti_town_neighbors", [CampRemnants,CoralReef]];
		CoralReef setVariable ["cti_town_neighbors", [lleSainteMarie,TikiHotel,SaintPaul]];
		TikiHotel setVariable ["cti_town_neighbors", [CoralReef,HotelResort]];
		HotelResort setVariable ["cti_town_neighbors", [TikiHotel,Aerodrome]];
		OuaQueLumberyard setVariable ["cti_town_neighbors", [HarborRemnants,Nicolet,Georgetown]];
		Nicolet setVariable ["cti_town_neighbors", [OuaQueLumberyard,SaintPaul]];
		SaintPaul setVariable ["cti_town_neighbors", [CoralReef,Nicolet,LaRochelle,Galili]];
		LaRochelle setVariable ["cti_town_neighbors", [SaintPaul,Aerodrome,CommsAlpha]];
		Aerodrome setVariable ["cti_town_neighbors", [HotelResort,LaRochelle,IndustrialPort]];
		IndustrialPort setVariable ["cti_town_neighbors", [Aerodrome,Vatukoulo,CommsBravo]];
		Galili setVariable ["cti_town_neighbors", [SaintPaul,CommsAlpha,Tanouka]];
		CommsAlpha setVariable ["cti_town_neighbors", [LaRochelle,CommsBravo,Galili]];
		CommsBravo setVariable ["cti_town_neighbors", [CommsAlpha,Vagalala,IndustrialPort]];
		Vatukoulo setVariable ["cti_town_neighbors", [IndustrialPort,Luganville,Vagalala]];
		Georgetown setVariable ["cti_town_neighbors", [OuaQueLumberyard,TempleOfDeath,Regina]];
		TempleOfDeath setVariable ["cti_town_neighbors", [Georgetown,Tanouka]];
		Tanouka setVariable ["cti_town_neighbors", [Galili,TempleOfDeath,Vagalala,AeroportdeTanoa]];
		Vagalala setVariable ["cti_town_neighbors", [Vatukoulo,CommsBravo,Tanouka,Lakatoro]];
		Regina setVariable ["cti_town_neighbors", [Georgetown,Sosovu,AeroportdeTanoa]];
		AeroportdeTanoa setVariable ["cti_town_neighbors", [Regina,Tanouka,Lumberyard]];
		Lakatoro setVariable ["cti_town_neighbors", [Lumberyard,Vagalala]];
		Lumberyard setVariable ["cti_town_neighbors", [AeroportdeTanoa,Lakatoro,Plantation,Kotomo]];
		Plantation setVariable ["cti_town_neighbors", [Lumberyard,Oumere]];
		Kotomo setVariable ["cti_town_neighbors", [Harcourt,Lumberyard,Oumere]];
		Oumere setVariable ["cti_town_neighbors", [FuelDepot,Kotomo,Plantation,Luganville]];
		Luganville setVariable ["cti_town_neighbors", [Vatukoulo,Oumere]];
	};
};

switch (toLower(worldName)) do {
	case "chernarus": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Pavlovo, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye]];
		Kamyshovo setVariable ["cti_town_neighbors", [Solnichniy, Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Kamyshovo, Msta, Nizhnoye, Dolina, Orlovets, Tulga]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, PobedaDam]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, PobedaDam, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Komarovo, Zelenogorsk]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Solnichniy, Polana]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, NovySobor, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Pustoshka]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		PobedaDam setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];		
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Gorka, Altar]];
	};
};