//---TownNeighborsSystem

switch (toLower(worldName)) do {
	case "altis": {
		Selakano setVariable ["cti_town_neighbors",[Feres,ComPlatform]];
		Pyrgos setVariable ["cti_town_neighbors",[SubPen,Faronaki,Ekali,Dorida]];
		Dorida setVariable ["cti_town_neighbors",[Chalkeia,Pyrgos,Charkia]];
		Charkia setVariable ["cti_town_neighbors",[Rodopoli,Dorida,Anthrakia]];
		Kalochori setVariable ["cti_town_neighbors",[Paros,Limni]];
		Rodopoli setVariable ["cti_town_neighbors",[Kalithea,Paros,Charkia]];
		Paros setVariable ["cti_town_neighbors",[Rodopoli,Loannina,MilitaryOutpost,Limni,Kalochori]];
		Molos setVariable ["cti_town_neighbors",[Sofia,ResearchPlatform,MolosAirfield]];
		Anthrakia setVariable ["cti_town_neighbors",[Telos,Charkia,SubPen]];
		Telos setVariable ["cti_town_neighbors",[Military,Kalithea,Anthrakia]];
		Athira setVariable ["cti_town_neighbors",[Military,Ifestiona,Frini]];
		Koroni setVariable ["cti_town_neighbors",[Galati,Ifestiona,Lakka]];
		Galati setVariable ["cti_town_neighbors",[Koroni,Syrta,NorthAirfield]];
		Oreokastro setVariable ["cti_town_neighbors",[NorthAirfield,AgiosKonstantinos,TheDump]];
		Syrta setVariable ["cti_town_neighbors",[Kore,AgiosDionysios,Galati,TheDump]];
		AgiosDionysios setVariable ["cti_town_neighbors",[Lakka,Zaros,Kore,Syrta]];
		Lakka setVariable ["cti_town_neighbors",[Neochori,AirBase,Koroni,AgiosDionysios]];
		Neochori setVariable ["cti_town_neighbors",[AirBase,Lakka,Military,SubPen,AACAirfield]];
		Zaros setVariable ["cti_town_neighbors",[AgiosDionysios,AACAirfield,Vikos,Panochori]];
		Kavala setVariable ["cti_town_neighbors",[Panochori,WindFarm,Stadium]];
		Airbase setVariable ["cti_town_neighbors",[Neochori,Lakka,Military,SubPen]];
		Military setVariable ["cti_town_neighbors",[Athira,Telos,Airbase]];
		Chalkeia setVariable ["cti_town_neighbors",[Dorida,Panagia,Limni]];
		Ifestiona setVariable ["cti_town_neighbors",[Koroni,Athira,Frini]];
		Negades setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kore,Stadium]];
		Sofia setVariable ["cti_town_neighbors",[Molos,Nidasos,Loannina]];
		Panagia setVariable ["cti_town_neighbors",[Chalkeia,Feres,Ekali]];
		Kore setVariable ["cti_town_neighbors",[Syrta,AgiosDionysios,Negades]];
		SandAirfield setVariable ["cti_town_neighbors",[Loannina]];
		Makrynisi setVariable ["cti_town_neighbors",[Faronaki,Neochori,AACAirfield]];
		Faronaki setVariable ["cti_town_neighbors",[Ekali,Vikos,Makrynisi,Pyrgos]];
		Kalithea setVariable ["cti_town_neighbors",[Rodopoli,Telos]];
		Vikos setVariable ["cti_town_neighbors",[Zaros,Faronaki,ComPlatform,OilRig]];
		Ekali setVariable ["cti_town_neighbors",[Panagia,Faronaki,ComPlatform,Pyrgos]];
		Frini setVariable ["cti_town_neighbors",[Ifestiona,Nychi,Athira,RadarPlatform]];
		Nychi setVariable ["cti_town_neighbors",[TheaterRuins,FuelDepot,Frini]];
		TheaterRuins setVariable ["cti_town_neighbors",[FuelDepot,MilitaryOutpost,Nychi]];
		MilitaryOutpost setVariable ["cti_town_neighbors",[TheaterRuins,Paros,HotelComplex]];
		NorthAirfield setVariable ["cti_town_neighbors",[Galati,Oreokastro,RadarPlatform]];
		Loannina setVariable ["cti_town_neighbors",[SandAirfield,Sofia,HotelComplex,Paros]];
		AACAirfield setVariable ["cti_town_neighbors",[Zaros,Neochori,Makrynisi]];
		MolosAirfield setVariable ["cti_town_neighbors",[FuelDepot,Molos]];
		Panochori setVariable ["cti_town_neighbors",[Kavala,Stadium,Zaros,OilRig]];
		HotelComplex setVariable ["cti_town_neighbors",[MilitaryOutpost,Loannina,Nidasos]];
		Stadium setVariable ["cti_town_neighbors",[Negades,Kavala,Panochori]];
		Limni setVariable ["cti_town_neighbors",[Paros,Chalkeia,ResearchPlatform]];
		AgiosKonstantinos setVariable ["cti_town_neighbors",[TheDump,Negades,Oreokastro,WindFarm]];
		Feres setVariable ["cti_town_neighbors",[Panagia,Selakano,ResearchPlatform]];
		Thedump setVariable ["cti_town_neighbors",[Oreokastro,Syrta,AgiosKonstantinos]];
		Nidasos setVariable ["cti_town_neighbors",[HotelComplex,Sofia]];
		SubPen setVariable ["cti_town_neighbors",[Neochori,Airbase,Anthrakia,Pyrgos]];
		ComPlatform setVariable ["cti_town_neighbors",[Ekali,Vikos,Selakano]];
		ResearchPlatform setVariable ["cti_town_neighbors",[Feres,Limni,Molos]];
		FuelDepot setVariable ["cti_town_neighbors",[RadarPlatform,Nychi,TheaterRuins,NorthAirfield]];
		OilRig setVariable ["cti_town_neighbors",[Vikos,Panochori]];
		RadarPlatform setVariable ["cti_town_neighbors",[NorthAirfield,Frini,FuelDepot]];
		WindFarm setVariable ["cti_town_neighbors",[AgiosKonstantinos,Kavala]];
	};
	case "stratis": {
		OutpostNorth setVariable ["cti_town_neighbors",[AgiaMarina,ComPlatform,KillFarm]];
		KillFarm setVariable ["cti_town_neighbors",[OutpostNorth,CampRogain,AgiaMarina]];
		AgiaMarina setVariable ["cti_town_neighbors",[OutpostNorth,KillFarm,StorageDump,TransmissionTowerBrit,AirBase,ComPlatform]];
		AirBase setVariable ["cti_town_neighbors",[ComPlatform,AgiaMarina,TransmissionTowerBrit,OysterBay,FuelDepot]];
		StorageDump setVariable ["cti_town_neighbors",[AgiaMarina,CampRogain,RadioControl,OldOutpost,TransmissionTowerBrit]];
		CampRogain setVariable ["cti_town_neighbors",[KillFarm,KaminoFiringRange,RadioControl,StorageDump]];
		RadioControl setVariable ["cti_town_neighbors",[StorageDump,CampRogain,KaminoFiringRange,LimeriBay,OldOutpost]];
		KaminoFiringRange setVariable ["cti_town_neighbors",[CampRogain,SubPen,RadioControl]];
		LimeriBay setVariable ["cti_town_neighbors",[RadioControl,SubPen,OldOutpost]];
		TransmissionTowerBrit setVariable ["cti_town_neighbors",[AgiaMarina,AirBase,StorageDump,OysterBay,OldOutpost]];
		OldOutpost setVariable ["cti_town_neighbors",[OysterBay,AirStationMike,StorageDump,RadioControl,TransmissionTowerBrit,LimeriBay]];
		CampTempest setVariable ["cti_town_neighbors",[OysterBay,Girna,FuelDepot,AirStationMike]];
		AirStationMike setVariable ["cti_town_neighbors",[OldOutpost,CampTempest,CampMaxwell,Tsoukalia]];
		OysterBay setVariable ["cti_town_neighbors",[AirBase,TransmissionTowerBrit,FuelDepot,CampTempest,OldOutpost]];
		Tsoukalia setVariable ["cti_town_neighbors",[AirStationMike,SubPen,CampMaxwell]];
		CampMaxwell setVariable ["cti_town_neighbors",[AirStationMike,LZConnor,Girna,Tsoukalia]];
		Girna setVariable ["cti_town_neighbors",[CampTempest,CampMaxwell,FuelDepot]];
		LZConnor setVariable ["cti_town_neighbors",[JayCove,CampMaxwell,SubPen]];
		JayCove setVariable ["cti_town_neighbors",[LZConnor,FuelDepot]];
		SubPen setVariable ["cti_town_neighbors",[LZConnor,Tsoukalia,LimeriBay,KaminoFiringRange]];
		ComPlatform setVariable ["cti_town_neighbors",[OutpostNorth,AirBase,AgiaMarina]];
		FuelDepot setVariable ["cti_town_neighbors",[CampTempest,Girna,OysterBay,JayCove,AirBase]];
	};
	case "tanoa": {
		Tuvanaka setVariable ["cti_town_neighbors", [TuvanakaAirbase,Belfort]];
		TuvanakaAirbase setVariable ["cti_town_neighbors", [Tuvanaka,CampRemnants]];
		Nani setVariable ["cti_town_neighbors", [Belfort,WindFarm,Sosovu]];
		Belfort setVariable ["cti_town_neighbors", [Tuvanaka,HarborRemnants,Nani]];
		HarborRemnants setVariable ["cti_town_neighbors", [Belfort,CampRemnants,OuaQueLumberyard]];
		CampRemnants setVariable ["cti_town_neighbors", [TuvanakaAirbase,HarborRemnants,lleSainteMarie]];
		WindFarm setVariable ["cti_town_neighbors", [Nani,Muaceba]];
		Sosovu setVariable ["cti_town_neighbors", [Muaceba,Regina]];
		Muaceba setVariable ["cti_town_neighbors", [WindFarm,Sosovu,Tavu,Balavu]];
		Tavu setVariable ["cti_town_neighbors", [Muaceba,Balavu,Laikoro]];
		Balavu setVariable ["cti_town_neighbors", [Muaceba,Tavu,Laikoro,Rautake]];
		Laikoro setVariable ["cti_town_neighbors", [Tavu,Balavu,Namuvaka]];
		Namuvaka setVariable ["cti_town_neighbors", [Laikoro,Rautake,Cerebu]];
		Rautake setVariable ["cti_town_neighbors", [Balavu,Namuvaka,Ferry]];
		Cerebu setVariable ["cti_town_neighbors", [Namuvaka,Yanukka]];
		Koumac setVariable ["cti_town_neighbors", [Lailai,Yanukka]];
		Yanukka setVariable ["cti_town_neighbors", [Lailai,Cerebu,Koumac]];
		Lailai setVariable ["cti_town_neighbors", [Katkoula,Yanukka,Koumac]];
		Ferry setVariable ["cti_town_neighbors", [Rautake,Katkoula]];
		Katkoula setVariable ["cti_town_neighbors", [Ferry,Savaka,Lailai]];
		Savaka setVariable ["cti_town_neighbors", [Katkoula,OilRig,Moddergat]];
		OilRig setVariable ["cti_town_neighbors", [Savaka,Moddergat,TuaduaIsland]];
		TuaduaIsland setVariable ["cti_town_neighbors", [OilRig,Blerick]];
		Moddergat setVariable ["cti_town_neighbors", [Savaka,OilRig,Losi,Blerick]];
		Losi setVariable ["cti_town_neighbors", [Moddergat,Harcourt]];
		Harcourt setVariable ["cti_town_neighbors", [Doodstil,Losi,Kotomo]];
		Doodstil setVariable ["cti_town_neighbors", [PortBoise,Harcourt,FuelDepot]];
		PortBoise setVariable ["cti_town_neighbors", [Lijnhaven,Rereki,Doodstil]];
		Lijnhaven setVariable ["cti_town_neighbors", [Blerick,PortBoise,Rereki]];
		Rereki setVariable ["cti_town_neighbors", [Lijnhaven,PortBoise]];
		Blerick setVariable ["cti_town_neighbors", [TuaduaIsland,Moddergat,Lijnhaven]];
		FuelDepot setVariable ["cti_town_neighbors", [Doodstil,Oumere]];
		lleSainteMarie setVariable ["cti_town_neighbors", [CampRemnants,CoralReef]];
		CoralReef setVariable ["cti_town_neighbors", [lleSainteMarie,TikiHotel,SaintPaul]];
		TikiHotel setVariable ["cti_town_neighbors", [CoralReef,HotelResort]];
		HotelResort setVariable ["cti_town_neighbors", [TikiHotel,Aerodrome]];
		OuaQueLumberyard setVariable ["cti_town_neighbors", [HarborRemnants,Nicolet,Georgetown]];
		Nicolet setVariable ["cti_town_neighbors", [OuaQueLumberyard,SaintPaul]];
		SaintPaul setVariable ["cti_town_neighbors", [CoralReef,Nicolet,LaRochelle,Galili]];
		LaRochelle setVariable ["cti_town_neighbors", [SaintPaul,Aerodrome,CommsAlpha]];
		Aerodrome setVariable ["cti_town_neighbors", [HotelResort,LaRochelle,IndustrialPort]];
		IndustrialPort setVariable ["cti_town_neighbors", [Aerodrome,Vatukoulo,CommsBravo]];
		Galili setVariable ["cti_town_neighbors", [SaintPaul,CommsAlpha,Tanouka]];
		CommsAlpha setVariable ["cti_town_neighbors", [LaRochelle,CommsBravo,Galili]];
		CommsBravo setVariable ["cti_town_neighbors", [CommsAlpha,Vagalala,IndustrialPort]];
		Vatukoulo setVariable ["cti_town_neighbors", [IndustrialPort,Luganville,Vagalala]];
		Georgetown setVariable ["cti_town_neighbors", [OuaQueLumberyard,TempleOfDeath,Regina]];
		TempleOfDeath setVariable ["cti_town_neighbors", [Georgetown,Tanouka]];
		Tanouka setVariable ["cti_town_neighbors", [Galili,TempleOfDeath,Vagalala,AeroportdeTanoa]];
		Vagalala setVariable ["cti_town_neighbors", [Vatukoulo,CommsBravo,Tanouka,Lakatoro,BloodRuins]];
		Regina setVariable ["cti_town_neighbors", [Georgetown,Sosovu,AeroportdeTanoa]];
		AeroportdeTanoa setVariable ["cti_town_neighbors", [Regina,Tanouka,Lumberyard]];
		Lakatoro setVariable ["cti_town_neighbors", [Lumberyard,Vagalala]];
		Lumberyard setVariable ["cti_town_neighbors", [AeroportdeTanoa,Lakatoro,BloodRuins,Kotomo]];
		BloodRuins setVariable ["cti_town_neighbors", [Lumberyard,Oumere,Vagalala]];
		Kotomo setVariable ["cti_town_neighbors", [Harcourt,Lumberyard,Oumere]];
		Oumere setVariable ["cti_town_neighbors", [FuelDepot,Kotomo,BloodRuins,Luganville]];
		Luganville setVariable ["cti_town_neighbors", [Vatukoulo,Oumere]];
	};
	case "chernarus": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Pavlovo, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka, FuelDepot]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye, WindFarm]];
		Kamyshovo setVariable ["cti_town_neighbors", [Solnichniy, Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Kamyshovo, Msta, Nizhnoye, Dolina, Orlovets, Tulga]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, PobedaDam]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, PobedaDam, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Komarovo, Zelenogorsk]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Solnichniy, Polana]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, NovySobor, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Pustoshka]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		PobedaDam setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Gorka, Altar]];
		WindFarm setVariable ["cti_town_neighbors", [Elektrozavodsk]];
		FuelDepot setVariable ["cti_town_neighbors", [Chernogorsk]];
	};
	case "chernarus_winter": {
		Kamenka setVariable ["cti_town_neighbors", [Pavlovo, Komarovo]];
		Komarovo setVariable ["cti_town_neighbors", [Pavlovo, Balota, Kamenka]];
		Balota setVariable ["cti_town_neighbors", [Kozlovka, Komarovo, Chernogorsk]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka]];
		Chernogorsk setVariable ["cti_town_neighbors", [Balota, Nadezhdino, Prigorodki, Kozlovka, Mogilevka]];
		Prigorodki setVariable ["cti_town_neighbors", [Chernogorsk, Elektrozavodsk, Pusta]];
		Elektrozavodsk setVariable ["cti_town_neighbors", [Prigorodki, Pusta, Kamyshovo, Staroye]];
		Kamyshovo setVariable ["cti_town_neighbors", [Solnichniy, Elektrozavodsk, Msta, Tulga]];
		Solnichniy setVariable ["cti_town_neighbors", [Kamyshovo, Msta, Nizhnoye, Dolina, Orlovets, Tulga]];
		Nizhnoye setVariable ["cti_town_neighbors", [Solnichniy, Berezino]];
		Berezino setVariable ["cti_town_neighbors", [Nizhnoye, Khelm, Orlovets, Dubrovka]];
		Khelm setVariable ["cti_town_neighbors", [Berezino, Krasnostav]];
		Krasnostav setVariable ["cti_town_neighbors", [Olsha, Gvozdno, Dubrovka, Khelm, PobedaDam]];
		Olsha setVariable ["cti_town_neighbors", [Krasnostav, Khelm]];
		Gvozdno setVariable ["cti_town_neighbors", [Krasnostav, Grishino, Dubrovka, PobedaDam, Altar, DevilsCastle]];
		Grishino setVariable ["cti_town_neighbors", [Gvozdno, Petrovka, Kabanino, AirField, Altar, DevilsCastle]];
		Petrovka setVariable ["cti_town_neighbors", [Grishino, Lopatino, Airfield, DevilsCastle]];
		Lopatino setVariable ["cti_town_neighbors", [Petrovka, Vybor, Pustoshka, Airfield]];
		Myshkino setVariable ["cti_town_neighbors", [Zelenogorsk, Pustoshka]];
		Zelenogorsk setVariable ["cti_town_neighbors", [Myshkino, Pogorevka, Kozlovka, Pavlovo]];
		Pavlovo setVariable ["cti_town_neighbors", [Kamenka, Komarovo, Zelenogorsk]];
		Kozlovka setVariable ["cti_town_neighbors", [Zelenogorsk, Nadezhdino, Chernogorsk, Balota, Pogorevka]];
		Nadezhdino setVariable ["cti_town_neighbors", [Kozlovka, Chernogorsk, Mogilevka, Vyshnoye]];
		Mogilevka setVariable ["cti_town_neighbors", [Vyshnoye, Pusta, Nadezhdino, Staroye, Chernogorsk]];
		Pusta setVariable ["cti_town_neighbors", [Mogilevka, Elektrozavodsk, Prigorodki, Staroye]];
		Staroye setVariable ["cti_town_neighbors", [Shakhovka, Guglovo, Elektrozavodsk, Msta, Mogilevka, Pusta]];
		Msta setVariable ["cti_town_neighbors", [Staroye, Kamyshovo, Solnichniy, Dolina, Tulga]];
		Dolina setVariable ["cti_town_neighbors", [Staroye, Solnichniy, Solnichniy, Polana]];
		Orlovets setVariable ["cti_town_neighbors", [Nizhnoye, Polana, Dolina, Solnichniy]];
		Polana setVariable ["cti_town_neighbors", [Orlovets, Dolina, Shakhovka, Gorka]];
		Gorka setVariable ["cti_town_neighbors", [Dubrovka, NovySobor, Polana, Guglovo, Altar]];
		Dubrovka setVariable ["cti_town_neighbors", [Gorka, Krasnostav, Berezino, Khelm, Altar]];
		Shakhovka setVariable ["cti_town_neighbors", [Staroye, Polana, Dolina]];
		Guglovo setVariable ["cti_town_neighbors", [Staroye, NovySobor, Shakhovka, Vyshnoye]];
		Vyshnoye setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Mogilevka, Nadezhdino, Pogorevka]];
		StarySobor setVariable ["cti_town_neighbors", [Vyshnoye, Kabanino, Pogorevka, NovySobor]];
		Pogorevka setVariable ["cti_town_neighbors", [Zelenogorsk, StarySobor, Vyshnoye, Pustoshka, Pustoshka]];
		Kabanino setVariable ["cti_town_neighbors", [Vybor, Grishino, StarySobor, Pogorevka]];
		Vybor setVariable ["cti_town_neighbors", [Kabanino, Lopatino, Pustoshka, Pogorevka]];
		Pustoshka setVariable ["cti_town_neighbors", [Vybor, Myshkino, Lopatino, Pogorevka]];
		PobedaDam setVariable ["cti_town_neighbors", [Gvozdno, Krasnostav]];
		Airfield setVariable ["cti_town_neighbors", [Vybor, Lopatino, Kabanino, Petrovka, Grishino]];
		Tulga setVariable ["cti_town_neighbors", [Solnichniy, Kamyshovo, Msta]];
		Altar setVariable ["cti_town_neighbors", [NovySobor, Gorka, Gvozdno]];
		DevilsCastle setVariable ["cti_town_neighbors", [Grishino, Gvozdno, Petrovka]];
		NovySobor setVariable ["cti_town_neighbors", [StarySobor, Guglovo, Gorka, Altar]];
	};
	case "sara_dbe1": {
		IslaDelVida setVariable ["cti_town_neighbors",[Hunapu,WorkCamp,FuelDepot]];
		Hunapu setVariable ["cti_town_neighbors",[IslaDelVida,WorkCamp,Pacamac]];
		WorkCamp setVariable ["cti_town_neighbors",[IslaDelVida,Hunapu,Malaredo]];
		Pacamac setVariable ["cti_town_neighbors",[Hunapu,Malaredo,Tlaloc,OilRig]];
		Malaredo setVariable ["cti_town_neighbors",[WorkCamp,Pacamac,RockQuarry,Epomia]];
		RockQuarry setVariable ["cti_town_neighbors",[Malaredo,RocaDelDror]];
		RocaDelDror setVariable ["cti_town_neighbors",[Epomia,RockQuarry,Antigua]];
		Epomia setVariable ["cti_town_neighbors",[Malaredo,RocaDelDror,Carmen]];
		Carmen setVariable ["cti_town_neighbors",[Epomia,Tlaloc,Bagango]];
		Tlaloc setVariable ["cti_town_neighbors",[Pacamac,OilRig,Carmen,Mercalillo]];
		Benoma setVariable ["cti_town_neighbors",[Bagango,Masbee]];
		Bagango setVariable ["cti_town_neighbors",[Mercalillo,Obregan,Benoma,Carmen]];
		Mercalillo setVariable ["cti_town_neighbors",[Tlaloc,Bagango,Obregan]];
		Masbee setVariable ["cti_town_neighbors",[Antigua,Benoma,Pita,TresValles]];
		Pita setVariable ["cti_town_neighbors",[Masbee,TresValles]];
		TresValles setVariable ["cti_town_neighbors",[Masbee,Pita,Everon]];
		Everon setVariable ["cti_town_neighbors",[TresValles,Obregan,Modesta,WindFarm]];
		Obregan setVariable ["cti_town_neighbors",[Mercalillo,Bagango,Everon,Modesta]];
		Modesta setVariable ["cti_town_neighbors",[Everon,Corazol,Obregan]];
		Corazol setVariable ["cti_town_neighbors",[Modesta,Ortego,Paraiso]];
		Rashidah setVariable ["cti_town_neighbors",[Paraiso,Chantico,OilRig]];
		Paraiso setVariable ["cti_town_neighbors",[Corazol,Somato,Rashidah]];
		Somato setVariable ["cti_town_neighbors",[Paraiso,Chantico,Cayo]];
		Chantico setVariable ["cti_town_neighbors",[Rashidah,Somato,Estrella]];
		Estrella setVariable ["cti_town_neighbors",[Chantico,FuelDepot,Arcadia]];
		Arcadia setVariable ["cti_town_neighbors",[Estrella,Cayo,Rahmandi]];
		Cayo setVariable ["cti_town_neighbors",[Somato,Arcadia,Iguana,Dolores]];
		Iguana setVariable ["cti_town_neighbors",[Cayo,Dolores,Rahmandi,WindFarm]];
		Dolores setVariable ["cti_town_neighbors",[Cayo,Iguana,Ortego,WindFarm]];
		Ortego setVariable ["cti_town_neighbors",[Corazol,Dolores]];
		Antigua setVariable ["cti_town_neighbors",[RocaDelDror,Masbee]];
		Rahmandi setVariable ["cti_town_neighbors",[Arcadia,Iguana,FuelDepot,WindFarm]];
		FuelDepot setVariable ["cti_town_neighbors",[IslaDelVida,Estrella,Rahmandi,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[Tlaloc,Pacamac,Rashidah,FuelDepot]];
		WindFarm setVariable ["cti_town_neighbors",[Rahmandi,Everon,Iguana,Dolores]];
	};
	case "takistan": {
		Nur setVariable ["cti_town_neighbors", [Nagara]];
		Nagara setVariable ["cti_town_neighbors", [Nur,Shamali,Gospandi,Rasman]];
		Shamali setVariable ["cti_town_neighbors", [Nagara,Rasman]];
		Rasman setVariable ["cti_town_neighbors", [Nagara,Bastam,Shamali,Zavarak]];
		Gospandi setVariable ["cti_town_neighbors", [Nagara,Mulladost,Bastam]];
		Mulladost setVariable ["cti_town_neighbors", [Gospandi,Khushab]];
		Khushab setVariable ["cti_town_neighbors", [Mulladost, Jilavur]];
		Jilavur setVariable ["cti_town_neighbors", [Khushab,Sakhe,FeruzAbad,Shukurkalay]];
		Shukurkalay setVariable ["cti_town_neighbors", [Jilavur, Chaman]];
		Chaman setVariable ["cti_town_neighbors", [Shukurkalay]];
		Sakhe setVariable ["cti_town_neighbors", [Jilavur,ChakChak,FeruzAbad,Kakaru]];
		ChakChak setVariable ["cti_town_neighbors", [Sakhe,Landay,Huzrutimam,Kakaru]];
		Landay setVariable ["cti_town_neighbors", [ChakChak]];
		Huzrutimam setVariable ["cti_town_neighbors", [ChakChak,Sultansafe]];
		Sultansafe setVariable ["cti_town_neighbors", [Huzrutimam,LoyManara]];
		LoyManara setVariable ["cti_town_neighbors", [Sultansafe,Jaza,Chardarakht,Timurkalay]];
		Jaza setVariable ["cti_town_neighbors", [LoyManara,Chardarakht]];
		Chardarakht setVariable ["cti_town_neighbors", [Jaza,LoyManara,HazarBagh]];
		HazarBagh setVariable ["cti_town_neighbors", [Chardarakht]];
		Timurkalay setVariable ["cti_town_neighbors", [LoyManara,Anar,Garmarud]];
		Anar setVariable ["cti_town_neighbors", [Timurkalay,FeruzAbad,Kakaru,Falar]];
		FeruzAbad setVariable ["cti_town_neighbors", [Jilavur,Anar,Sakhe,Kakaru,Falar]];
		Kakaru setVariable ["cti_town_neighbors", [FeruzAbad,ChakChak,Anar,Sakhe]];
		Falar setVariable ["cti_town_neighbors", [FeruzAbad,Anar,Bastam]];
		Bastam setVariable ["cti_town_neighbors", [Rasman,Gospandi,Falar,Imarat]];
		Imarat setVariable ["cti_town_neighbors", [Bastam,Zavarak,Garmarud]];
		Garmarud setVariable ["cti_town_neighbors", [Imarat,Timurkalay,Garmsar]];
		Garmsar setVariable ["cti_town_neighbors", [Garmarud]];
		Zavarak setVariable ["cti_town_neighbors", [Imarat,Ravanay,Karachinar,Rasman]];
		Ravanay setVariable ["cti_town_neighbors", [Zavarak,Karachinar]];
		Karachinar setVariable ["cti_town_neighbors", [Zavarak,Ravanay]];
	};
	case "beketov": {
		Sentsy setVariable ["cti_town_neighbors",[OutpostJordan,KrasyneSeltsy]];
		KrasyneSeltsy setVariable ["cti_town_neighbors",[Shalaevo,Sentsy,Polshishkino]];
		Polivanovo setVariable ["cti_town_neighbors",[Shalaevo,Zhukovo,Polshishkino]];
		Polshishkino setVariable ["cti_town_neighbors",[Shalaevo,KrasyneSeltsy,Zhukovo,Polshishkino,Mikhalevo]];
		Zhukovo setVariable ["cti_town_neighbors",[Polivanovo,Polshishkino,Kuzhadon]];
		Kuzhadon setVariable ["cti_town_neighbors",[Zhukovo,Armanikha,Shpagino]];
		Shpagino setVariable ["cti_town_neighbors",[Kuzhadon,NorthWestBeketov]];
		Armanikha setVariable ["cti_town_neighbors",[Kuzhadon,NorthWestBeketov]];
		NorthWestBeketov setVariable ["cti_town_neighbors",[SouthBeketov,EastBeketov,Armanikha,Shpagino]];
		SouthBeketov setVariable ["cti_town_neighbors",[NorthWestBeketov,EastBeketov]];
		EastBeketov setVariable ["cti_town_neighbors",[NorthWestBeketov,SouthBeketov,Gavrikolvka]];
		Gavrikolvka setVariable ["cti_town_neighbors",[EastBeketov,Sevastianovo,Dorogino]];
		Sevastianovo setVariable ["cti_town_neighbors",[Gavrikolvka,Siukha,Mikhalevo]];
		Mikhalevo setVariable ["cti_town_neighbors",[Polshishkino,Siukha,Sevastianovo]];
		Siukha setVariable ["cti_town_neighbors",[Mikhalevo,LakeEusovo,Sevastianovo,Vorontsovo]];
		Dorogino setVariable ["cti_town_neighbors",[Gavrikolvka,LakeEusovo,Imeni,Naleskino]];
		Imeni setVariable ["cti_town_neighbors",[Dorogino,LakeEusovo,Naleskino]];
		Naleskino setVariable ["cti_town_neighbors",[Dorogino,Imeni,Vizovino]];
		Vizovino setVariable ["cti_town_neighbors",[Dorogino,Vizovino]];	
		LakeEusovo setVariable ["cti_town_neighbors",[Dorogino,Imeni,Siukha,Studenets]];
		Vorontsovo setVariable ["cti_town_neighbors",[Studenets,Siukha,Arshavino]];
		Studenets  setVariable ["cti_town_neighbors",[Vorontsovo,LakeEusovo,Arshavino]];
		Arshavino setVariable ["cti_town_neighbors",[Vorontsovo,Studenets,Dubionki]];
		Dubionki setVariable ["cti_town_neighbors",[Arshavino,OutpostJordan]];
		OutpostJordan setVariable ["cti_town_neighbors",[Dubionki,Sentsy]];
		Shalaevo setVariable ["cti_town_neighbors",[Polivanovo,Polshishkino,KrasyneSeltsy]];
	};
	case "napf": {
		Bernerplatte setVariable ["cti_town_neighbors",[Airbase,Feldmoos]];
		Feldmoos setVariable ["cti_town_neighbors",[Bernerplatte,Worb]];
		Worb setVariable ["cti_town_neighbors",[Feldmoos,Airbase,Hindelbank,Signau]];
		Hindelbank setVariable ["cti_town_neighbors",[Worb,FuelDepot,Muttenz,Huttwil]];
		FuelDepot setVariable ["cti_town_neighbors",[Hindelbank,Bubendorf,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[FuelDepot,Seltisberg,Hafen]];
		Bubendorf setVariable ["cti_town_neighbors",[Huttwil,FuelDepot,Seltisberg]];
		Huttwil setVariable ["cti_town_neighbors",[Hindelbank,Muttenz,Bubendorf,NeueWelt]];
		Seltisberg setVariable ["cti_town_neighbors",[Bubendorf,NeueWelt,OilRig,Trueb,Lenzburg]];
		NeueWelt setVariable ["cti_town_neighbors",[Huttwil,Seltisberg,Trueb]];
		Muttenz setVariable ["cti_town_neighbors",[Signau,Hindelbank,Huttwil]];
		Signau setVariable ["cti_town_neighbors",[Eggwil,Worb,Muttenz,Chatzbach]];
		Chatzbach setVariable ["cti_town_neighbors",[Ramsebode,Bruderholz,Signau]];
		Eggwil setVariable ["cti_town_neighbors",[Airbase,Schangen,Signau]];
		Airbase setVariable ["cti_town_neighbors",[Bernerplatte,Worb,Eggwil,Schangen]];
		Hungerschwand setVariable ["cti_town_neighbors",[Schangen,Goldwil]];
		Schangen setVariable ["cti_town_neighbors",[Airbase,Hungerschwand,Schrattendamm,Eggwil,Ramsebode]];
		Schrattendamm setVariable ["cti_town_neighbors",[Schangen,Sorenberg]];
		Goldwil setVariable ["cti_town_neighbors",[Hungerschwand,Brienz,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors",[Goldwil,Brienz,SouthAirstrip]];
		Brienz setVariable ["cti_town_neighbors",[Goldwil,WindFarm,Froburg,Sorenberg]];
		Froburg setVariable ["cti_town_neighbors",[Brienz,SouthAirstrip,Griswil]];
		SouthAirstrip setVariable ["cti_town_neighbors",[Froburg,WindFarm]];
		Griswil setVariable ["cti_town_neighbors",[Froburg,Village,Sorenberg]];
		Village setVariable ["cti_town_neighbors",[Griswil,Alpnach]];
		Sorenberg setVariable ["cti_town_neighbors",[Griswil,Brienz,Farnen,Schrattendamm]];
		Farnen setVariable ["cti_town_neighbors",[Sorenberg,Liestal]];
		Ramsebode setVariable ["cti_town_neighbors",[Schangen,Liestal,Chatzbach,Bruderholz]];
		Bruderholz setVariable ["cti_town_neighbors",[Ramsebode,Chatzbach,NapfCastle]];
		Eichmatt setVariable ["cti_town_neighbors",[Trueb,NapfCastle]];
		Lenzburg setVariable ["cti_town_neighbors",[Seltisberg,Trueb,Hafen,Olten]];
		Hafen setVariable ["cti_town_neighbors",[OilRig,Lenzburg,Olten]];
		Olten setVariable ["cti_town_neighbors",[Lenzburg,Hafen,Lausen,Hirsegg]];
		Hirsegg setVariable ["cti_town_neighbors",[Trueb,Olten,Lausen,NapfCastle]];
		Lausen setVariable ["cti_town_neighbors",[Olten,Hirsegg,Luzern,InternationalAir]];
		NapfCastle setVariable ["cti_town_neighbors",[Hirsegg,Eichmatt,Bruderholz,Romoos]];
		Liestal setVariable ["cti_town_neighbors",[Sachseln,Ramsebode,Farnen,Romoos,Wolhusen]];
		Schimbrig setVariable ["cti_town_neighbors",[Alpnach,Sachseln]];
		Alpnach setVariable ["cti_town_neighbors",[Village,Schimbrig,Pfeffikon]];
		Sachseln setVariable ["cti_town_neighbors",[Schimbrig,Liestal,Wolhusen]];
		Romoos setVariable ["cti_town_neighbors",[NapfCastle,Liestal,Wolhusen]];
		Wolhusen setVariable ["cti_town_neighbors",[Romoos,Luzern,Liestal,Sachseln,Horw]];
		Luzern setVariable ["cti_town_neighbors",[Lausen,Wolhusen,InternationalAir,Horw]];
		Horw setVariable ["cti_town_neighbors",[Luzern,InternationalAir,Pfeffikon,Wolhusen]];
		InternationalAir setVariable ["cti_town_neighbors",[Luzern,Lausen,Horw,Suhrenfeld]];
		Suhrenfeld setVariable ["cti_town_neighbors",[Pfeffikon,InternationalAir]];
		Pfeffikon setVariable ["cti_town_neighbors",[Horw,Suhrenfeld,Alpnach]];
		Trueb setVariable ["cti_town_neighbors",[Hirsegg,Seltisberg,NeueWelt,Lenzburg,Eichmatt]];

	};
	case "napfwinter": {
		Bernerplatte setVariable ["cti_town_neighbors",[Airbase,Feldmoos]];
		Feldmoos setVariable ["cti_town_neighbors",[Bernerplatte,Worb]];
		Worb setVariable ["cti_town_neighbors",[Feldmoos,Airbase,Hindelbank,Signau]];
		Hindelbank setVariable ["cti_town_neighbors",[Worb,FuelDepot,Muttenz,Huttwil]];
		FuelDepot setVariable ["cti_town_neighbors",[Hindelbank,Bubendorf,OilRig]];
		OilRig setVariable ["cti_town_neighbors",[FuelDepot,Seltisberg,Hafen]];
		Bubendorf setVariable ["cti_town_neighbors",[Huttwil,FuelDepot,Seltisberg]];
		Huttwil setVariable ["cti_town_neighbors",[Hindelbank,Muttenz,Bubendorf,NeueWelt]];
		Seltisberg setVariable ["cti_town_neighbors",[Bubendorf,NeueWelt,OilRig,Trueb,Lenzburg]];
		NeueWelt setVariable ["cti_town_neighbors",[Huttwil,Seltisberg,Trueb]];
		Muttenz setVariable ["cti_town_neighbors",[Signau,Hindelbank,Huttwil]];
		Signau setVariable ["cti_town_neighbors",[Eggwil,Worb,Muttenz,Chatzbach]];
		Chatzbach setVariable ["cti_town_neighbors",[Ramsebode,Bruderholz,Signau]];
		Eggwil setVariable ["cti_town_neighbors",[Airbase,Schangen,Signau]];
		Airbase setVariable ["cti_town_neighbors",[Bernerplatte,Worb,Eggwil,Schangen]];
		Hungerschwand setVariable ["cti_town_neighbors",[Schangen,Goldwil]];
		Schangen setVariable ["cti_town_neighbors",[Airbase,Hungerschwand,Schrattendamm,Eggwil,Ramsebode]];
		Schrattendamm setVariable ["cti_town_neighbors",[Schangen,Sorenberg]];
		Goldwil setVariable ["cti_town_neighbors",[Hungerschwand,Brienz,WindFarm]];
		WindFarm setVariable ["cti_town_neighbors",[Goldwil,Brienz,SouthAirstrip]];
		Brienz setVariable ["cti_town_neighbors",[Goldwil,WindFarm,Froburg,Sorenberg]];
		Froburg setVariable ["cti_town_neighbors",[Brienz,SouthAirstrip,Griswil]];
		SouthAirstrip setVariable ["cti_town_neighbors",[Froburg,WindFarm]];
		Griswil setVariable ["cti_town_neighbors",[Froburg,Village,Sorenberg]];
		Village setVariable ["cti_town_neighbors",[Griswil,Alpnach]];
		Sorenberg setVariable ["cti_town_neighbors",[Griswil,Brienz,Farnen,Schrattendamm]];
		Farnen setVariable ["cti_town_neighbors",[Sorenberg,Liestal]];
		Ramsebode setVariable ["cti_town_neighbors",[Schangen,Liestal,Chatzbach,Bruderholz]];
		Bruderholz setVariable ["cti_town_neighbors",[Ramsebode,Chatzbach,NapfCastle]];
		Eichmatt setVariable ["cti_town_neighbors",[Trueb,NapfCastle]];
		Lenzburg setVariable ["cti_town_neighbors",[Seltisberg,Trueb,Hafen,Olten]];
		Hafen setVariable ["cti_town_neighbors",[OilRig,Lenzburg,Olten]];
		Olten setVariable ["cti_town_neighbors",[Lenzburg,Hafen,Lausen,Hirsegg]];
		Hirsegg setVariable ["cti_town_neighbors",[Trueb,Olten,Lausen,NapfCastle]];
		Lausen setVariable ["cti_town_neighbors",[Olten,Hirsegg,Luzern,InternationalAir]];
		NapfCastle setVariable ["cti_town_neighbors",[Hirsegg,Eichmatt,Bruderholz,Romoos]];
		Liestal setVariable ["cti_town_neighbors",[Sachseln,Ramsebode,Farnen,Romoos,Wolhusen]];
		Schimbrig setVariable ["cti_town_neighbors",[Alpnach,Sachseln]];
		Alpnach setVariable ["cti_town_neighbors",[Village,Schimbrig,Pfeffikon]];
		Sachseln setVariable ["cti_town_neighbors",[Schimbrig,Liestal,Wolhusen]];
		Romoos setVariable ["cti_town_neighbors",[NapfCastle,Liestal,Wolhusen]];
		Wolhusen setVariable ["cti_town_neighbors",[Romoos,Luzern,Liestal,Sachseln,Horw]];
		Luzern setVariable ["cti_town_neighbors",[Lausen,Wolhusen,InternationalAir,Horw]];
		Horw setVariable ["cti_town_neighbors",[Luzern,InternationalAir,Pfeffikon,Wolhusen]];
		InternationalAir setVariable ["cti_town_neighbors",[Luzern,Lausen,Horw,Suhrenfeld]];
		Suhrenfeld setVariable ["cti_town_neighbors",[Pfeffikon,InternationalAir]];
		Pfeffikon setVariable ["cti_town_neighbors",[Horw,Suhrenfeld,Alpnach]];
		Trueb setVariable ["cti_town_neighbors",[Hirsegg,Seltisberg,NeueWelt,Lenzburg,Eichmatt]];

	};
};
